# using regex find/replace in Sublime Text 4
# ^\s+?'([1-9a-zA-Z\.\s,\*\-/]+)',?$
# '\1': '\1',

problem_timestrings = [
    '24+29:614',
    3401.0,
    9414.0,
    'MED4',
    'SWA5431',
    'ASA787'
]

problem_datestrings = [
    4,
    7,
    55
]

fixes_injury = {
    '*NO': 'NO',
    'GREEN': 'UNKNOWN',
    'MP': 'NO',
    'NO': 'NO',
    'NO*': 'NO',
    'UNK': 'UNKNOWN',
    'UNKN': 'UNKNOWN',
    'YES': 'YES'
}


fixes_states = {
    'ALABAMA': 'ALABAMA',
    'ALASKA': 'ALASKA',
    'ARIZONA': 'ARIZONA',
    'ARKANSAS': 'ARKANSAS',
    'CALIFIORNIA': 'CALIFORNIA',
    'CALIFORNIA': 'CALIFORNIA',
    'CHICAGO': 'ILLINOIS',
    'COLORADO': 'COLORADO',
    'CONNECTICUT': 'CONNECTICUT',
    'D.C.': 'DISTRICT OF COLUMBIA',
    'DC': 'DISTRICT OF COLUMBIA',
    'DELAWARE': 'DELAWARE',
    'DISTRICT OF COLUMBIA': 'DISTRICT OF COLUMBIA',
    'FLORIDA': 'FLORIDA',
    'GEORGIA': 'GEORGIA',
    'GUAM': 'GUAM',
    'HAWAII': 'HAWAII',
    'IDAHO': 'IDAHO',
    'ILLINOIS': 'ILLINOIS',
    'INDIANA': 'INDIANA',
    'IOWA': 'IOWA',
    'KANSAS': 'KANSAS',
    'KENTUCKY': 'KENTUCKY',
    'LOUISIANA': 'LOUISIANA',
    'MAINE': 'MAINE',
    'MARIANA ISLANDS': 'NORTHERN MARIANA ISLANDS',
    'MARINA ISLANDS': 'NORTHERN MARIANA ISLANDS',
    'MARYLAND': 'MARYLAND',
    'MASSACHUSETTS': 'MASSACHUSETTS',
    'MASSACHUSSETS': 'MASSACHUSETTS',
    'MEXICO': 'MEXICO',
    'MIAMI': 'MIAMI',
    'MICHIGAN': 'MICHIGAN',
    'MICRONESIA': 'MICRONESIA',
    'MINNESOTA': 'MINNESOTA',
    'MISSISSIPPI': 'MISSISSIPPI',
    'MISSOURI': 'MISSOURI',
    'MONTANA': 'MONTANA',
    'NEBRASKA': 'NEBRASKA',
    'NEVADA': 'NEVADA',
    'NEW HAMPSHIRE': 'NEW HAMPSHIRE',
    'NEW JERSEY': 'NEW JERSEY',
    'NEW MEXICO': 'NEW MEXICO',
    'NEW YORK': 'NEW YORK',
    'NORTH CAROLINA': 'NORTH CAROLINA',
    'NORTH DAKOTA': 'NORTH DAKOTA',
    'NORTH HAMPSHIRE': 'NORTH HAMPSHIRE',
    'NORTHERN MARIANA IS': 'NORTHERN MARIANA ISLANDS',
    'NORTHERN MARIANA ISLAND': 'NORTHERN MARIANA ISLANDS',
    'NORTHERN MARIANAS IS': 'NORTHERN MARIANA ISLANDS',
    'NORTHERN MARINA ISLANDS': 'NORTHERN MARIANA ISLANDS',
    'OHIO': 'OHIO',
    'OHO': 'OHIO',
    'OKLAHOMA': 'OKLAHOMA',
    'OREGON': 'OREGON',
    'PENNSYLVANIA': 'PENNSYLVANIA',
    'PITTSBURGH': 'PENNSYLVANIA',
    'PUERTO RICO': 'PUERTO RICO',
    'RHODE ISLAND': 'RHODE ISLAND',
    'SOUTH CAROLINA': 'SOUTH CAROLINA',
    'SOUTH DAKOTA': 'SOUTH DAKOTA',
    'ST CROIX': 'ST, CROIX',
    'TEAS': 'TEXAS',
    'TENNESSEE': 'TENNESSEE',
    'TEXAS': 'TEXAS',
    'U.S. VIRGIN ISLANDS': 'U.S. VIRGIN ISLANDS',
    'UNKN': 'UNKNOWN',
    'UTAH': 'UTAH',
    'VA': 'VIRGINIA',
    'VERMONT': 'VERMONT',
    'VIRGIN ISLANDS': 'VIRGIN ISLANDS',
    'VIRGINIA': 'VIRGINIA',
    'WASHINGTON': 'WASHINGTON',
    'WEST VIRGINIA': 'WEST VIRGINIA',
    'WISCONSIN': 'WISCONSIN',
    'WYOMING': 'WYOMING'
}


fixes_colors = {
    '2 green': 'green',
    'amber': 'amber',
    'blue': 'blue',
    'blue  and  purple': 'blue,purple',
    'blue -green': 'blue,green',
    'blue and green': 'blue,green',
    'blue and purple': 'blue,purple',
    'blue and red': 'blue,red',
    'blue and violet': 'blue,violet',
    'blue and white': 'blue,white',
    'blue and white green': 'blue,green,white',
    'blue or green': 'blue,green',
    'blue or purple': 'blue,purple',
    'blue or white': 'blue,white',
    'blue-green': 'blue,green',
    'blue-purple': 'blue,purple',
    'blue-red': 'blue,red',
    'blue-white': 'blue,white',
    'blue-yellow': 'blue,yellow',
    'blue/green': 'blue,green',
    'blue/purple': 'blue,purple',
    'blue/red': 'blue,red',
    'blue/red/green': 'blue,green,red',
    'blue/white': 'blue,white',
    'bluish green': 'blue,green',
    'bright blue': 'blue',
    'continuous green': 'green',
    'dark blue': 'blue',
    'fireworks': 'unknown',
    'gray': 'gray',
    'green': 'green',
    'green - 2': 'green',
    'green and blue': 'blue,green',
    'green and blue and white': 'blue,green,white',
    'green and multi-colored': 'green,multiple',
    'green and orange': 'green,orange',
    'green and pink': 'green,pink',
    'green and purple': 'green,purple',
    'green and red': 'green,red',
    'green and red and blue': 'blue,green,red',
    'green and white': 'green,white',
    'green and white and red': 'green,red,white',
    'green and yellow': 'green,yellow',
    'green or blue': 'blue,green',
    'green or red': 'green,red',
    'green or white': 'green,white',
    'green red blue': 'blue,green,red',
    'green white': 'green,white',
    'green, blue and red': 'blue,green,red',
    'green, blue or purple': 'blue,green,purple',
    'green, purple and red': 'green,purple,red',
    'green, red and blue': 'blue,green,red',
    'green-blue': 'blue,green',
    'green-purple': 'green,purple',
    'green-red': 'green,red',
    'green-white': 'green,white',
    'green-yellow': 'green,yellow',
    'green/ blue': 'blue,green',
    'green/blue': 'blue,green',
    'green/orange': 'green,orange',
    'green/purple': 'green,purple',
    'green/red': 'green,red',
    'green/red/blue': 'blue,green,red',
    'green/red/white': 'green,red,white',
    'green/white': 'green,white',
    'green/yellow': 'green,yellow',
    'grey/white': 'gray,white',
    'intense white': 'white',
    'laser': 'unknown',
    'lavender': 'lavender',
    'light blue': 'blue',
    'light yellow': 'yellow',
    'magenta': 'magenta',
    'multi': 'multiple',
    'multi colored': 'multiple',
    'multi-color': 'multiple',
    'multi-colored': 'multiple',
    'multicolor': 'multiple',
    'multicolored': 'multiple',
    'multiple': 'multiple',
    'multiple green and white': 'green,white',
    'one green and one blue': 'blue,green',
    'orange': 'orange',
    'orange-red': 'orange,red',
    'orange/red': 'orange,red',
    'orange/white': 'orange,white',
    'orange/yellow': 'orange,yellow',
    'phx': 'unknown',
    'purple': 'purple',
    'purple and blue': 'blue,purple',
    'purple and green': 'green,purple',
    'purple and red': 'purple,red',
    'purple or blue': 'blue,purple',
    'purple-blue': 'blue,purple',
    'purple/blue': 'blue,purple',
    'purple/white': 'purple,white',
    'red': 'red',
    'red and blue': 'blue,red',
    'red and green': 'green,red',
    'red and purple': 'purple,red',
    'red and white': 'red,white',
    'red or green': 'green,red',
    'red white and blue': 'blue,red,white',
    'red, blue, and green': 'blue,green,red',
    'red, green and purple': 'green,purple,red',
    'red, green, white': 'green,red,white',
    'red, white and blue': 'blue,red,white',
    'red, white, blue and green': 'blue,green,red,white',
    'red, white, green': 'green,red,white',
    'red-green': 'green,red',
    'red-white': 'red,white',
    'red/green': 'green,red',
    'red/green/blue': 'blue,green,red',
    'red/white/blue': 'blue,red,white',
    'spotlight': 'unknown',
    'two green': 'green',
    'unk': 'unknown',
    'unkn': 'unknown',
    'unknown': 'unknown',
    'unkwn': 'unknown',
    'violet': 'violet',
    'white': 'white',
    'white and blue': 'blue,white',
    'white and blue green': 'blue,green,white',
    'white and green': 'green,white',
    'white and purple': 'purple,white',
    'white and purple and blue': 'blue,purple,white',
    'white and yellow': 'white,yellow',
    'white or amber': 'amber,white',
    'white or green': 'green,white',
    'white spotlight followed by a green': 'green,white',
    'white strobe': 'white',
    'white strobing': 'white',
    'white, blue, purple and green': 'blue,green,purple,white',
    'white-blue': 'blue,white',
    'white-green': 'green,white',
    'white-green-red': 'green,red,white',
    'white-red': 'red,white',
    'white-yellow': 'white,yellow',
    'white/green': 'green,white',
    'white/red': 'red,white',
    'white/yellow': 'white,yellow',
    'yellow': 'yellow',
    'yellow and green': 'green,yellow',
    'yellow and red': 'red,yellow',
    'yellow and white': 'white,yellow',
    'yellow-white': 'white,yellow',
    'yellow/orange': 'orange,yellow',
    'yellow/white': 'white,yellow'
}
